-- ------------------------------------------------------------
-- Table: customers
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS customers (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
);

-- ------------------------------------------------------------
-- Table: support_tickets
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS support_tickets (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT       NOT NULL,
    raw_query   TEXT         NOT NULL,
    status      VARCHAR(50)  NOT NULL DEFAULT 'OPEN',
    intent      VARCHAR(50)  NULL,
    urgency     VARCHAR(50)  NULL,
    resolution  TEXT         NULL,
    created_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE
);

-- ------------------------------------------------------------
-- Table: knowledge_base
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS knowledge_base (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_chunk TEXT NOT NULL,
    embedding     BLOB NULL
);

-- ------------------------------------------------------------
-- Seed Demo Customers (for immediate use without registration)
-- ------------------------------------------------------------
MERGE INTO customers (name, email)
    KEY (email)
    VALUES
        ('Dharan Kumar',    'dharan@example.com'),
        ('Alice Johnson',   'alice@example.com'),
        ('Bob Martinez',    'bob@example.com'),
        ('Clara Williams',  'clara@example.com'),
        ('David Chen',      'david@example.com');

-- ------------------------------------------------------------
-- Knowledge Base (Static reference data — not user seed data)
-- ------------------------------------------------------------
INSERT INTO knowledge_base (content_chunk, embedding)
    SELECT 'Refund policy: Customers may request a full refund within 30 days of purchase.', NULL
    WHERE NOT EXISTS (SELECT 1 FROM knowledge_base WHERE content_chunk LIKE 'Refund policy%');
INSERT INTO knowledge_base (content_chunk, embedding)
    SELECT 'Technical support hours are Monday through Friday, 9 AM to 6 PM EST.', NULL
    WHERE NOT EXISTS (SELECT 1 FROM knowledge_base WHERE content_chunk LIKE 'Technical support hours%');
INSERT INTO knowledge_base (content_chunk, embedding)
    SELECT 'Account management: Customers can update billing information via the portal.', NULL
    WHERE NOT EXISTS (SELECT 1 FROM knowledge_base WHERE content_chunk LIKE 'Account management%');
INSERT INTO knowledge_base (content_chunk, embedding)
    SELECT 'Shipping policy: Standard delivery takes 5-7 business days. Express delivery available within 2 days.', NULL
    WHERE NOT EXISTS (SELECT 1 FROM knowledge_base WHERE content_chunk LIKE 'Shipping policy%');
INSERT INTO knowledge_base (content_chunk, embedding)
    SELECT 'Password reset: Visit account settings or use the Forgot Password link on the login page.', NULL
    WHERE NOT EXISTS (SELECT 1 FROM knowledge_base WHERE content_chunk LIKE 'Password reset%');
